### PR TITLE
Error handling on initial key load

### PR DESCRIPTION
**Pull request by domportera**
It was failing to load for me after creating some PuTTY-style ssh key stuff for SourceTree, so I put in some super-simple error handling on the startup loading method

### CODE REVIEW

**Comment by frequency403** [comment]
Thank you for your Contribution! I will consider applying further Error handling in the entire program. 

Can you provide a key like the one that caused the application to fail? 
Maybe then i can prevent errors being thrown.

**Comment by domportera** [comment]
certainly! it seems like anything created by [PuttyGen](https://www.puttygen.com/) - they have their own key format denoted by the .ppk extension. i made the public key have a `.pub` file extension to follow normal ssh stuff but that doesnt seem required or standard?

either way i have little use for this but anyone who uses sourcetree/mercurial might run into this issue

[puttygen-keys.zip](https://github.com/frequency403/OpenSSH-GUI/files/15077705/puttygen-keys.zip)

**Comment by frequency403** [comment]
Feel free to check out the development branch right now. 
Run the app - it should support Putty Keys and OpenSSH keys now.

**Comment by domportera** [comment]
thank you! It seems like my PuTTY keys still aren't loaded, though it's not crashing on startup (which is all I really cared about anyway 😅) I'll attach an example pair I tested with, though I don't personally need you to address the issue -
[putty-keys.zip](https://github.com/user-attachments/files/15522203/putty-keys.zip). The public file is the one without an extension (thanks putty for having backwards defaults -_-)

**Pull request merged**
